apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sepp-app
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/telco/apps/sepp
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
